abstract final class ApiEndpoints {
  static const login = '/auth/login';
  static const refreshToken = '/auth/refresh';
  static const logout = '/auth/logout';

  static const products = '/master/products';
  static const outlets = '/master/outlets';
  static const visits = '/visits';
  static const visitActivities = '/visit-activities';
  static const notifications = '/notifications';
  static const meetings = '/meetings';
  static const salesOrders = '/sales-orders';
  static const checkIns = '/visits/check-in';
  static const checkOuts = '/visits/check-out';
  static const purchases = '/purchases';
  static const returns = '/returns';
  static const gifts = '/gifts';
  static const outletNotes = '/outlet-notes';
  static const receivablePayments = '/receivable-payments';
  static const deferVisit = '/visits/defer';
  static const cancelVisit = '/visits/cancel';
  static const visitApprovals = '/approvals/visits';
  static const dashboard = '/dashboard';
  static const approvals = '/approvals';
  static const serverState = '/sync/state';
  static const promotions = '/promotions';
  static const files = '/files';
  static const monitoringActivities = '/monitoring/sales-activities';
  static const monitoringVisits = '/monitoring/visits';
  static const monitoringPerformance = '/monitoring/performance';
  static const reportsSummary = '/reports/summary';
  static const attachments = '/attachments';
  static const masterSnapshot = '/master/snapshot';
  static const routeEstimate = '/routes/estimate';
  static const journeys = '/journeys';
  static const deliveryNotes = '/delivery-notes';
  static const deliveryNoteApprovals = '/approvals/delivery-notes';
}
